In [1]:
import numpy as np

In [4]:
a = np.arange(64).reshape(4,4,4)

In [5]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [9]:
a[0][2,0]

8

In [30]:
a[[0:1,2:,0][1]]

SyntaxError: invalid syntax (<ipython-input-30-7f852aede840>, line 1)

In [32]:
b = np.array([[1,2,3,4],[11,12,13,14]])

In [33]:
b

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [34]:
b[1,1] # indexing

12

In [39]:
b[1:,1]# slicing

array([12])

In [40]:
b.shape

(2, 4)

In [41]:
a[1,2,3]

27